<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
$formData = $block->getCustomer();
$dob = '';
if ($formData && $formData->getDob()) {
    try {
        $dob = (new \DateTime($formData->getDob()))->format('d/m/Y');
    } catch (\Exception $e) {
        $dob = '';
    }
}
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('rokanbase/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $block->escapeHtml(__('Account Information')) ?></span></legend><br>

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()) : ?>
            <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
        <?php endif ?>

        <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>

        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_dob->isEnabled()) : ?>
          <div class="field date field-dob required">
                <label for="dob" class="label">
                    <span><?= $block->escapeHtml(__('Date of Birth')) ?>:</span>
                </label>
                <div class="control">
                    <input
                        type="text"
                        name="dob"
                        id="dob"
                        value="<?= $block->escapeHtmlAttr($dob) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Date of Birth')) ?>"
                        class=""
                        data-validate="{required:true, 'validate-dob-format':true}">
                </div>
            </div>
        <?php endif ?>
        <?php
            echo $this->getLayout()
            ->createBlock('Careshop\Customcustomer\Block\Phone')
            ->setTemplate('Careshop_Customcustomer::additional.phtml')
            ->toHtml();
        ?>
        <?php if ($_taxvat->isEnabled()) : ?>
            <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
        <?php endif ?>
        <div class="field choice">
            <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
            <label class="label" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
        </div>
        <div class="field choice">
            <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
            <label class="label" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
        </div>
    </fieldset>

    <fieldset class="fieldset password" data-container="change-email-password">
        <legend class="legend"><span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span></legend><br>
        <div class="field email required" data-container="change-email">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" />
            </div>
        </div>
        <div class="field password current required">
            <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
            </div>
        </div>
        <div class="field new password required" data-container="new-password">
            <label class="label" for="password"><span><?= $block->escapeHtml(__('New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password" id="password"
                    data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                    data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                    data-input="new-password"
                    data-validate="{required:true, 'validate-customer-password':true}"
                    autocomplete="off" />
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        <?= $block->escapeHtml(__('Password Strength')) ?>:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                            <?= $block->escapeHtml(__('No Password')) ?>
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="field confirmation password required" data-container="confirm-password">
            <label class="label" for="password-confirmation"><span><?= $block->escapeHtml(__('Confirm New Password')) ?></span></label>
            <div class="control">
                <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                    data-input="confirm-password"
                    autocomplete="off" />
            </div>
        </div>
    </fieldset>
    <?= $block->getChildHtml('form_additional_info') ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Cancel')) ?></span></a>
        </div>
        <div class="secondary">
            <button type="button" class="action save primary disabled" title="<?= $block->escapeHtmlAttr(__('Save')) ?>" disabled><span><?= $block->escapeHtml(__('Save')) ?></span></button>
        </div>
    </div>
</form>
<script>
    require([
        "jquery",
        "mage/mage"
    ], function($) {
        var dataForm = $('#form-validate');
        var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

        $('.action.save').prop('disabled', true).addClass('disabled');

        dataForm.on('input', ':input', function() {
            // Enable save button if there's a change
            $('.action.save').prop('disabled', false).removeClass('disabled');
        });


        // dataForm.mage('validation', {
        //     </?php if ($_dob->isEnabled()) : ?>
        //     errorPlacement: function(error, element) {
        //         if (element.prop('id').search('full') !== -1) {
        //             var dobElement = $(element).parents('.customer-dob'),
        //                 errorClass = error.prop('class');
        //             error.insertAfter(element.parent());
        //             dobElement.find('.validate-custom').addClass(errorClass)
        //                 .after('<div class="' + errorClass + '"></div>');
        //         } else {
        //             error.insertAfter(element);
        //         }
        //     },
        //     ignore: ':hidden:not(' + ignore + ')'
        //     </?php else : ?>
        //     ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
        //     </?php endif ?>
        // });
    });
</script>
<script type="text/x-magento-init">
    {
        "[data-role=change-email], [data-role=change-password]": {
            "changeEmailPassword": {
                "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
                "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
                "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
            }
        },
        "[data-container=new-password]": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-edit-account"
            }
        }
    }
</script>
<div id="popup-modal-confirmation-email-my-account">
    <h3><?= $block->escapeHtml(__('After confirmation, an email for the change will be sent. Please click the link when you get it.')) ?></h3>
</div>

<script type="text/javascript">
require([
   'jquery',
   'mage/calendar'
], function($) {
   $(document).ready(function() {


       $('#dob').calendar({
           dateFormat: "dd/mm/yy",
           yearRange: "-120y:c+nn",
           maxDate: "-1d",
           changeMonth: true,
           changeYear: true,
           showOn: "both",
           mask: true,
           onSelect: function(dateText, inst) {

               $('.ui-datepicker-calendar td').removeClass('selected');
               $('.ui-state-default').removeClass('ui-state-active');
               $(inst.dpDiv).find('td[data-year="' + inst.selectedYear + '"][data-month="' + inst.selectedMonth + '"]')
                            .filter(function() {
                                return $(this).text() === inst.selectedDay.toString();
                            }).addClass('selected');

       $('.action.save').prop('disabled', false).removeClass('disabled');





           }
       });
       $('#dob').on('input', function() {
           var currentDate = new Date();
           var dobValue = $(this).val();

           if (dobValue) {
               var dobParts = dobValue.split('/');
               var dobDate = new Date(dobParts[2], parseInt(dobParts[1]) - 1, dobParts[0]);

               if (dobDate > currentDate) {
                   $(this).val('');
                   alert("Please enter a past date");
               }
       }
       });
   });
});
</script>
<style>

.ui-datepicker .ui-datepicker-title .ui-datepicker-month {
    width: 47%;
    height: 40px !important;
	margin-right: unset;
}
.ui-datepicker-title{
    display: flex;
    align-items: center;
    gap: 10px;
}
.field.gender .control .label {
	margin-right: 30px !important;
}


.ui-datepicker-calendar .selected {
    background-color: #ffdf66 !important;
}


.ui-datepicker .ui-datepicker-calendar td .ui-state-hover {
    background: #ffdf66;
}

.ui-datepicker {
    width: 290px !important;
}

.ui-datepicker-trigger{
    display: flex !important;
    position: absolute;
    float: right;
    right: 54px;
    margin-top: -45px !important;
}

/* Media query for larger screens */
@media (min-width: 576px) and (max-width: 786px) {
    .ui-datepicker-trigger {
        right: 23px;
    }
}

@media (max-width: 576px) {
    .ui-datepicker-trigger {
        right: 5px;
        margin-top: -44px !important;
    }
}



</style>
