<div class="block account-nav">
    <div class="title account-nav-title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div>
    <div class="content account-nav-content" id="account-nav">
        <ul class="nav items">
        <li class="nav item current"><strong><a href="<?= $block->escapeUrl($block->getUrl('customer/account')) ?>"><?= $block->escapeHtml(__('My Account')) ?></a></strong></li>
            <li class="nav item">
                <a href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>"><?= $block->escapeHtml(__('My Orders')) ?></a>
            </li>
			
			<li class="nav item"><a href="<?= $block->escapeUrl($block->getUrl('wishlist')) ?>"><?= $block->escapeHtml(__('Wish List')) ?></a></li>
					
          
           
            <li class="nav item"><a href="<?= $block->escapeUrl($block->getUrl('reviews/index/index')) ?>"><?= $block->escapeHtml(__('Reviews
                    / Improvements')) ?></a></li>
           
             <li class="nav item"><a href="<?= $block->escapeUrl($block->getUrl('returns-and-warranty')) ?>"><?= $block->escapeHtml(__('Returns
                    &amp; Warranty')) ?></a>
            </li>
            
           
         
            <li class="nav item"><a href="<?= $block->escapeUrl($block->getUrl('review/customer')) ?>"><?= $block->escapeHtml(__('My Product Reviews')) ?></a></li>
            
       
			
			<li class="nav item"><a href="<?= $block->escapeUrl($block->getUrl('affiliate/affiliate/home')) ?>"><?= $block->escapeHtml(__('Affiliate')) ?></a>
            </li>
			
        </ul>
    </div>
</div>