<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     data-role="collapsible" id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>">
                    <a class="data switch custom-hover"
                       tabindex="-1"
                       data-toggle="trigger"
                       href="#<?= $block->escapeUrl($alias) ?>"
                       id="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title">
                        <?= /* @noEscape */ $label ?>
                    </a>
                </div>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>" data-role="content">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>


<style>
  .catalog-product-view.product-container-right.product.info.detailed.product.data.items >.item.title a {
    color: #0D0D0D;
    height: auto;
    border: 0;
    background: #ECF1F4;
    font-size: 16px;
    font-weight: 500;
    padding: 4.5px 20px;
    min-width: 17rem;
    text-align: center;
    border-radius: 0;
    border: 1px solid #B8CAD5;
    border-right: 1px!important;
    position: relative;
}


.product.data.items .data.switch:hover {
  background: #e1e1e1 !important;
}
.data.item.title.active .custom-hover:hover {
  background: #f05735 !important;
}

#tab-label-reviews-title {

 border-left: 0px !important;
  
  border-radius: 0 10px 10px 0 !important; 
}

.catalog-product-view .product-container-right .product.info.detailed .product.data.items > .item.title:first-child a{

    border-radius: 10px 0 0 10px !important;
    

}


    </style>