<?php
/**
* Copyright © Magento, Inc. All rights reserved.
* See COPYING.txt for license details.
*/


/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses">




<div class="block-content">
     
       <div class="box box-shipping-address">
           <strong class="box-title">
               <span><?= $block->escapeHtml(__('Default Shipping & Billing Address')) ?></span>
           </strong>
           <div class="box-content">
               <address>
                   <?= $block->getPrimaryShippingAddressHtml() ?>
               </address>
           </div>
           <div class="box-actions">
               <a class="action edit" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link"><span><?= $block->escapeHtml(__('Change Shipping & Billing Address')) ?></span></a>
           </div>
       </div>
   </div>
</div>




<?php
echo $this->getLayout()->createBlock('Careshop\Customaddress\Block\Address\Grid')->setTemplate('Magento_Customer::address/grid.phtml')->toHtml();