<?php
use Magento\Framework\App\Action\Action;

$_productCollection = $block->getProducts();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$pricingHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class);
?>
<div class="rokan-newproduct-folk grid products-grid">
    <?php
    $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $pos = $block->getPositioned();
    ?>
    <?php if (!$_productCollection->getSize()): ?>
    <div class="rokan-newproduct-slider">
        <p class="note-msg"><?= $block->escapeHtml(__('There are no products matching the selection.')); ?></p>
    </div>
    <?php else: ?>
    <div class="rokan-product-heading rokan-onsale-heading">
        <h2><?= $block->escapeHtml(__('Folks who viewed this item also viewed')); ?></h2>
    </div>
    <div class="who-viewed-this-item-also-viewed owl-carousel owl-theme" data-buttonsplaypause="true" data-rtl="false"
        data-items="4" data-bigdesktop="4" data-smalldesktop="4" data-bigtablet="3" data-tablet="3"
        data-smalltablet="2" data-mobile="1" data-margin="28" data-loop="true" data-center="false"
        data-mousedrag="true" data-touchdrag="true" data-stagepadding="1" data-nav="true" data-navnext="Next"
        data-navprev="Prev" data-rewind="true" data-dots="false" data-lazyload="false" data-autoplay="false"
        data-autoplaytimeout="3000" data-autoplayhoverpause="false" data-speed="250">
        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <div class='item product-items'>
            <div class="product-item">
                <div class="product-item-info ">
                    <?php
                        $productImage = $block->getImage($_product, $image);
                        ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                        class="product photo product-item-photo" tabindex="-1">
                        <?= /* @noEscape */ $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= $block->escapeHtml(
                                        $_helper->productAttribute($_product, $_product->getName(), 'name')
                                    ); ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <div class="original-price-instead-of-common">
                            <?php
                                    $original_price = $_product->getData('original_price');
                                ?>
                            <?= $block->escapeHtml(
                                    __('Instead of').': '.$pricingHelper->currency($original_price, true, false)
                                ); ?>
                        </div>
                        <div class="product-ratting">
                            <?= /* @noEscape */ $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        </div>
                    </div>
                    <?php $i++;?>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>
</div>