<div class="footer-container">
	<div class="footer-top">
		<div class="footer-newsletter"><div class="container"><?= $this->getChildHtml("subscribe"); ?></div></div>
		<div class="container">
			<div class="container-inner">
					<div class="footer-static_text footer-careshop">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static_text')->toHtml(); ?>
					</div>
					<div class="footer-static_link">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static_link')->toHtml(); ?>
					</div>
					<div class="footer-static_payment">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static_payment')->toHtml(); ?>
					</div>
					<div class="footer-static_social footer-careshop">
						<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static_social')->toHtml(); ?>
					</div>
			</div>
		</div>
	</div>
	<div class="footer-bottom">
		<div class="container">
			<div class="container-inner">
				<div class="bottom_link">
					<?= $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom_link')->toHtml(); ?>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="coming-soon-pupup-container-fixed" style="display:none;">
	<div class="fixed-content-pupup-coming-soon">
		<h4><?= __('We are nearly complete.');?></h4>
		<p>This function will be coming soon!</p>
	</div>
</div>