<?php
/**
 * @var \Careshop\RokanthemesBrand\ViewModel\Brand $brandViewModel
 */

$item = $block->getItem();
$product = $item->getProduct();
$brandViewModel = $block->getData('brand_view_model');
$brand = $brandViewModel->getBrandCollection($product);
?>
<div class="product-item-info-name">
    <?php if (isset($brand['image_url']) && $brand['image_url']) { ?>
        <div class="brands">
            <img src="<?= $brand['image_url']; ?>" alt="<?= $brand['value'] ?>" class="brand-thumbnail">
        </div>
    <?php }?>
    <p class="product-item-name">
        <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
           class="product-item-link"
        >
            <?= $block->escapeHtml($product->getName()) ?>
        </a>
    </p>
    <?= /** @noEscape */ $block->getChildBlock('item_options')->setItem($item)->toHtml() ?>
</div>
